// GENERATED by @wonder-wagon/themes/adapters/terminal — do not edit.
// Source: @wonder-wagon/themes@0.1.0, theme "forge", night signal #C8973F.
// Regenerate with the product's sync script; verify with its --check. Values hash: 2ab160ec.

/** The product's serial and the family maker's mark: stated once, printed small. */
export const SERIAL = "FG-047";

/** The one identity colour, in every alphabet a terminal speaks. Severity never uses it. */
export const BRAND = Object.freeze({
  hex: "#C8973F",
  truecolor: "\u001b[38;2;200;151;63m",
  ansi256: "\u001b[38;5;173m",
  ansi16: "\u001b[33m",
});

/** Severity maps to the terminal's own colours, which render the same everywhere. */
export const SEVERITY = Object.freeze({
  ok: "green",
  info: "cyan",
  warn: "yellow",
  bad: "red",
});

export const VALUES_HASH = "2ab160ec";
